In [3]:
import numpy as np

In [4]:
a=np.array([[4,5,6],[1,2,3]],dtype='int64')

In [5]:
print(a)

[[4 5 6]
 [1 2 3]]


In [6]:
a.ndim

2

In [7]:
a.shape

(2, 3)

In [8]:
a.size

6

In [9]:
a.itemsize

8

In [15]:
L1=[1,2,3]
L2=[4,5,6]

In [16]:
L1+L2

[1, 2, 3, 4, 5, 6]

In [17]:
L1*2

[1, 2, 3, 1, 2, 3]

In [18]:
L1*L2

TypeError: can't multiply sequence by non-int of type 'list'

In [20]:
a.reshape(3,2)

array([[4, 5],
       [6, 1],
       [2, 3]], dtype=int16)

In [27]:
a = np.array((((1, 2, 3), (4, 5, 6)), ((2, 3, 5), (1, 7, 8))))
print(a.ndim)

3


In [28]:
s="this is a python program"

In [55]:
s[8:1:-1]

'a si si'

In [53]:
s[::-1]

'margorp nohtyp a si siht'

In [59]:
s[4::1]

' is a python program'

In [58]:
s[:2:1]

'th'

In [60]:
a=np.array([[4,5,6],[1,2,3]])

In [95]:
a[0,:2]

array([4, 5])

In [101]:
a=np.max([1,2,3,4,5,6])
print(a)

6


In [102]:
a=np.mean([1,2,3,4,5,6])
print(a)

3.5


In [103]:
a=np.sqrt([1,2,3,4,5,6])
print(a)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [105]:
a=np.std([1,2,3,4,5,6])
print(a)

1.707825127659933


In [106]:
a=np.sum([1,2,3,4,5,6])
print(a)

21


In [116]:
a=np.arange(10,15,2)
print(a)

[10 12 14]


In [127]:
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [123]:
a=np.ones(3)
print(a)

[1. 1. 1.]


In [128]:
import pandas as pd

In [132]:
df=pd.read_csv("finds.csv")

In [136]:
df.head

<bound method NDFrame.head of    Area  Price
0   100   1000
1   200   1800
2   300   2500
3   400   2700
4   500   3000>

In [134]:
df.tail

<bound method NDFrame.tail of    Area  Price
0   100   1000
1   200   1800
2   300   2500
3   400   2700
4   500   3000>

In [142]:
df.head(4)

Area  Price
0   100   1000
1   200   1800
2   300   2500
3   400   2700

In [139]:
df.sample

<bound method NDFrame.sample of    Area  Price
0   100   1000
1   200   1800
2   300   2500
3   400   2700
4   500   3000>

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Area    5 non-null      int64
 1   Price   5 non-null      int64
dtypes: int64(2)
memory usage: 212.0 bytes


In [146]:
df.describe()

Area       Price
count    5.000000     5.00000
mean   300.000000  2200.00000
std    158.113883   803.11892
min    100.000000  1000.00000
25%    200.000000  1800.00000
50%    300.000000  2500.00000
75%    400.000000  2700.00000
max    500.000000  3000.00000

In [151]:
df.columns

Index(['Area', 'Price'], dtype='object')

In [156]:
df.Area

0    100
1    200
2    300
3    400
4    500
Name: Area, dtype: int64

In [159]:
df

Area  Price
0   100   1000
1   200   1800
2   300   2500
3   400   2700
4   500   3000

In [173]:
df['Price'].unique()

array([1000, 1800, 2500, 2700, 3000], dtype=int64)

In [174]:
df['Area'].unique()

array([100, 200, 300, 400, 500], dtype=int64)

In [180]:
df['Area'].value_counts()

Area
100    1
200    1
300    1
400    1
500    1
Name: count, dtype: int64

In [105]:
import numpy as np

In [106]:
import pandas as pd

In [107]:
df=pd.read_csv("dataa.csv")

In [108]:
df.describe()

time weather  temp company humidity    wind goes
count         4       4     4       4        4       4    4
unique        2       2     3       2        3       2    2
top     morning   sunny  cold     yes     mild  normal  yes
freq          2       3     2       3        2       3    3

In [109]:
df.sample

<bound method NDFrame.sample of       time weather      temp company humidity    wind goes
0  morning   sunny      warm     yes     mild  strong  yes
1  evening   rainy      cold      no     mild  normal   no
2  morning   sunny  moderate     yes   normal  normal  yes
3  evening   sunny      cold     yes     high  normal  yes>

In [110]:
print(df.head())

      time weather      temp company humidity    wind goes
0  morning   sunny      warm     yes     mild  strong  yes
1  evening   rainy      cold      no     mild  normal   no
2  morning   sunny  moderate     yes   normal  normal  yes
3  evening   sunny      cold     yes     high  normal  yes


In [111]:
d=np.array(df)[:,:-1]
print(d)

[['morning' 'sunny' 'warm' 'yes' 'mild' 'strong']
 ['evening' 'rainy' 'cold' 'no' 'mild' 'normal']
 ['morning' 'sunny' 'moderate' 'yes' 'normal' 'normal']
 ['evening' 'sunny' 'cold' 'yes' 'high' 'normal']]


In [112]:
t=np.array(df)[:,-1]
print(t)

['yes' 'no' 'yes' 'yes']


In [113]:
ps = df[df['goes'] == 'yes']
print(ps)

      time weather      temp company humidity    wind goes
0  morning   sunny      warm     yes     mild  strong  yes
2  morning   sunny  moderate     yes   normal  normal  yes
3  evening   sunny      cold     yes     high  normal  yes


In [114]:
hyp = ps.iloc[0, :-1].values
print(hyp)

['morning' 'sunny' 'warm' 'yes' 'mild' 'strong']


In [115]:
print("Initial hypothesis:", hyp)

Initial hypothesis: ['morning' 'sunny' 'warm' 'yes' 'mild' 'strong']


In [116]:
for index, row in ps.iterrows():
    print(f"\nProcessing positive sample {index + 1}: {row[:-1].values}")
    for i in range(len(hyp)):
        if hyp[i] != row.iloc[i]:
             hyp[i] = '?'
    print(f"Updated hypothesis after sample {index + 1}: {hyp}")
print("\nfinal hypothesis based on the positive samples:")
print(hyp)


Processing positive sample 1: ['morning' 'sunny' 'warm' 'yes' 'mild' 'strong']
Updated hypothesis after sample 1: ['morning' 'sunny' 'warm' 'yes' 'mild' 'strong']

Processing positive sample 3: ['morning' 'sunny' 'moderate' 'yes' 'normal' 'normal']
Updated hypothesis after sample 3: ['morning' 'sunny' '?' 'yes' '?' '?']

Processing positive sample 4: ['evening' 'sunny' 'cold' 'yes' 'high' 'normal']
Updated hypothesis after sample 4: ['?' 'sunny' '?' 'yes' '?' '?']

final hypothesis based on the positive samples:
['?' 'sunny' '?' 'yes' '?' '?']
