In [161]:
import numpy as np 

In [162]:
import pandas as pd

In [163]:
df=pd.read_csv("drug200.csv")

In [164]:
df

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [165]:
df.size


1200

In [166]:
df.shape

(200, 6)

In [167]:
x=df.iloc[:,0:-1].values

In [168]:
x

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.114],
       [28, 'F', 'NORMAL', 'HIGH', 7.798],
       [61, 'F', 'LOW', 'HIGH', 18.043],
       [22, 'F', 'NORMAL', 'HIGH', 8.607],
       [49, 'F', 'NORMAL', 'HIGH', 16.275],
       [41, 'M', 'LOW', 'HIGH', 11.037],
       [60, 'M', 'NORMAL', 'HIGH', 15.171],
       [43, 'M', 'LOW', 'NORMAL', 19.368],
       [47, 'F', 'LOW', 'HIGH', 11.767],
       [34, 'F', 'HIGH', 'NORMAL', 19.199],
       [43, 'M', 'LOW', 'HIGH', 15.376],
       [74, 'F', 'LOW', 'HIGH', 20.942],
       [50, 'F', 'NORMAL', 'HIGH', 12.703],
       [16, 'F', 'HIGH', 'NORMAL', 15.516],
       [69, 'M', 'LOW', 'NORMAL', 11.455],
       [43, 'M', 'HIGH', 'HIGH', 13.972],
       [23, 'M', 'LOW', 'HIGH', 7.298],
       [32, 'F', 'HIGH', 'NORMAL', 25.974],
       [57, 'M', 'LOW', 'NORMAL', 19.128],
       [63, 'M', 'NORMAL', 'HIGH', 25.917],
       [47, 'M', 'LOW', 'NORMAL', 30.568],
       [48, 'F', 'LOW',

In [169]:
y=df.iloc[:,-1].values

In [170]:
y

array(['drugY', 'drugC', 'drugC', 'drugX', 'drugY', 'drugX', 'drugY',
       'drugC', 'drugY', 'drugY', 'drugC', 'drugY', 'drugY', 'drugY',
       'drugX', 'drugY', 'drugX', 'drugA', 'drugC', 'drugY', 'drugY',
       'drugY', 'drugY', 'drugY', 'drugY', 'drugY', 'drugY', 'drugX',
       'drugY', 'drugY', 'drugX', 'drugB', 'drugX', 'drugY', 'drugX',
       'drugX', 'drugA', 'drugX', 'drugX', 'drugX', 'drugY', 'drugB',
       'drugY', 'drugX', 'drugX', 'drugX', 'drugA', 'drugC', 'drugY',
       'drugY', 'drugY', 'drugX', 'drugY', 'drugY', 'drugB', 'drugC',
       'drugB', 'drugY', 'drugX', 'drugY', 'drugY', 'drugA', 'drugY',
       'drugX', 'drugB', 'drugY', 'drugA', 'drugX', 'drugY', 'drugY',
       'drugB', 'drugY', 'drugX', 'drugY', 'drugY', 'drugY', 'drugA',
       'drugY', 'drugA', 'drugX', 'drugB', 'drugX', 'drugC', 'drugA',
       'drugC', 'drugB', 'drugX', 'drugY', 'drugY', 'drugY', 'drugY',
       'drugY', 'drugY', 'drugY', 'drugY', 'drugX', 'drugY', 'drugY',
       'drugY', 'dru

In [171]:
from sklearn.preprocessing import LabelEncoder

In [172]:
le=LabelEncoder()

In [173]:
for i in range(0,4):
    x[:,i]=le.fit_transform(x[:,i])

In [174]:
x

array([[8, 0, 0, 0, 25.355],
       [30, 1, 1, 0, 13.093],
       [30, 1, 1, 0, 10.114],
       [12, 0, 2, 0, 7.798],
       [44, 0, 1, 0, 18.043],
       [7, 0, 2, 0, 8.607],
       [32, 0, 2, 0, 16.275],
       [25, 1, 1, 0, 11.037],
       [43, 1, 2, 0, 15.171],
       [27, 1, 1, 1, 19.368],
       [30, 0, 1, 0, 11.767],
       [18, 0, 0, 1, 19.199],
       [27, 1, 1, 0, 15.376],
       [56, 0, 1, 0, 20.942],
       [33, 0, 2, 0, 12.703],
       [1, 0, 0, 1, 15.516],
       [52, 1, 1, 1, 11.455],
       [27, 1, 0, 0, 13.972],
       [8, 1, 1, 0, 7.298],
       [16, 0, 0, 1, 25.974],
       [40, 1, 1, 1, 19.128],
       [46, 1, 2, 0, 25.917],
       [30, 1, 1, 1, 30.568],
       [31, 0, 1, 0, 15.036],
       [17, 0, 1, 0, 33.486],
       [12, 0, 0, 1, 18.809],
       [15, 1, 0, 0, 30.366],
       [32, 0, 2, 1, 9.381],
       [23, 0, 1, 1, 22.697],
       [28, 1, 1, 0, 17.951],
       [3, 0, 2, 1, 8.75],
       [56, 1, 0, 0, 9.567],
       [32, 1, 1, 1, 11.014],
       [48, 0, 0, 1, 3

In [175]:
y=le.fit_transform(y)

In [176]:
y

array([4, 2, 2, 3, 4, 3, 4, 2, 4, 4, 2, 4, 4, 4, 3, 4, 3, 0, 2, 4, 4, 4,
       4, 4, 4, 4, 4, 3, 4, 4, 3, 1, 3, 4, 3, 3, 0, 3, 3, 3, 4, 1, 4, 3,
       3, 3, 0, 2, 4, 4, 4, 3, 4, 4, 1, 2, 1, 4, 3, 4, 4, 0, 4, 3, 1, 4,
       0, 3, 4, 4, 1, 4, 3, 4, 4, 4, 0, 4, 0, 3, 1, 3, 2, 0, 2, 1, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 0, 0, 2, 3, 4, 3, 3, 4, 1, 4,
       0, 3, 3, 3, 3, 4, 3, 3, 0, 4, 4, 4, 4, 4, 1, 4, 4, 3, 4, 3, 4, 4,
       3, 4, 4, 3, 1, 0, 1, 3, 0, 4, 1, 4, 0, 3, 3, 0, 3, 2, 0, 1, 3, 3,
       4, 2, 0, 4, 2, 3, 3, 1, 3, 4, 4, 4, 4, 3, 4, 0, 3, 3, 4, 4, 0, 4,
       0, 4, 4, 4, 4, 3, 3, 4, 4, 4, 1, 0, 4, 4, 4, 0, 4, 2, 4, 2, 2, 3,
       3, 3])

In [177]:
from sklearn.model_selection import train_test_split

In [178]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.23, random_state=21)

In [179]:
from sklearn.tree import DecisionTreeClassifier


In [180]:
model=DecisionTreeClassifier()

In [181]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [182]:
y_pred=model.predict(x_test)
y_pred


array([0, 4, 0, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 3, 4, 3, 0, 4, 0, 4, 1, 4,
       4, 3, 0, 4, 4, 3, 2, 4, 4, 4, 0, 4, 2, 4, 1, 4, 0, 1, 0, 3, 3, 3,
       3, 1])

In [183]:
x_test

array([[23, 1, 0, 0, 9.664],
       [27, 1, 1, 1, 19.368],
       [27, 1, 0, 0, 13.972],
       [40, 1, 1, 1, 19.128],
       [49, 0, 2, 1, 8.107],
       [32, 0, 2, 0, 16.275],
       [45, 1, 1, 1, 27.183],
       [25, 1, 0, 1, 15.156],
       [16, 0, 2, 0, 7.477],
       [20, 0, 0, 1, 15.49],
       [46, 1, 2, 0, 25.917],
       [33, 1, 2, 1, 15.79],
       [21, 1, 1, 1, 8.968],
       [44, 1, 2, 0, 9.443],
       [52, 1, 1, 0, 15.478],
       [38, 1, 2, 1, 7.261],
       [36, 0, 0, 1, 12.495],
       [13, 0, 0, 0, 29.45],
       [28, 0, 0, 0, 12.854],
       [56, 0, 1, 0, 20.942],
       [54, 1, 0, 1, 9.677],
       [11, 1, 1, 1, 20.909],
       [55, 0, 2, 0, 19.221],
       [8, 1, 2, 1, 14.02],
       [8, 1, 0, 0, 8.011],
       [54, 1, 1, 0, 16.31],
       [29, 0, 0, 0, 34.686],
       [24, 0, 2, 0, 10.103],
       [30, 1, 1, 0, 10.114],
       [35, 1, 1, 1, 32.922],
       [16, 0, 0, 1, 25.974],
       [56, 1, 0, 1, 15.436],
       [11, 0, 0, 1, 12.307],
       [30, 1, 1, 1, 30.5

In [184]:
y_test

array([0, 4, 0, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 3, 4, 3, 1, 4, 0, 4, 1, 4,
       4, 3, 0, 4, 4, 3, 2, 4, 4, 4, 0, 4, 2, 4, 1, 4, 1, 1, 0, 3, 3, 3,
       3, 1])

In [185]:
from sklearn.metrics import confusion_matrix , accuracy_score,precision_score,recall_score

In [186]:
p = precision_score(y_test, y_pred, average='macro') 
a = accuracy_score(y_test, y_pred)
r = recall_score(y_test, y_pred, average='macro')

In [187]:
print("accuracy : ",a*100)
print("precision is : ", p)
print("recall is : ",r)

accuracy :  95.65217391304348
precision is :  0.95
recall is :  0.9333333333333332
